#source: source
#destination: dist
port: 8888

#URL Prefixing
siteurl: https://innocellence.com
baseurl: /

#Encoding
encoding: UTF-8

#Plugins
plugins:
  - jekyll-redirect-from

#Permalinks
permalink: /:categories/:year/:month/:day/:slug/


#Exclude
exclude:
  - samples-helpers
  - jp-NEW
  - jp-NEW.html
